function f = compile(model, name, folder)
%COMPILE  Generate a MATLAB function from a parsed DAVE-ML model.
%   f = vital.daveml.compile(model, name, folder) writes <folder>/<name>.m:
%
%       out = <name>(in)
%
%   in   struct whose fields are input varIDs (model units, as published);
%        an input with an initialValue may be omitted, any other missing
%        input raises vital:daveml:missingInput
%   out  struct with EVERY variable by varID, plus out.outOfEnvelope (true
%        if any table input was clamped: OUT_OF_DATA_ENVELOPE)
%
%   Variables are evaluated in dependency order; minValue/maxValue are
%   applied as saturations after each assignment (ADR-014). Tables are
%   embedded as constants, so the generated file is self-contained and
%   deterministic (no timestamps): regenerating from the same source gives
%   a byte-identical file (tested in tF16CheckData).
arguments
    model (1,1) struct
    name (1,:) char
    folder (1,:) char
end
v = model.vars;
L = strings(0);
L(end+1) = sprintf('function out = %s(in)', name);
L(end+1) = sprintf('%%%s  GENERATED by vital.daveml.compile. DO NOT EDIT.', upper(name));
[~, fname, fext] = fileparts(model.file);
L(end+1) = sprintf('%%   Source: %s%s (%s)', fname, fext, model.name);
L(end+1) = sprintf('%%   Source SHA-256: %s', model.sha256);
L(end+1) = '%   Inputs and outputs are in the units declared by the source file.';
L(end+1) = '%   Regenerate with vital.aircraft.f16.generateModels (F-16) or vital.daveml.compile.';
L(end+1) = 'persistent K';
L(end+1) = 'if isempty(K)';
for k = 1:numel(model.functions)
    fn = model.functions(k);
    for b = 1:numel(fn.bps)
        L(end+1) = sprintf('    K.f%d_bp%d = %s;', k, b, vec(fn.bps{b})); %#ok<AGROW>
    end
    sz = size(fn.data);
    if numel(fn.bps) == 1
        L(end+1) = sprintf('    K.f%d_data = %s;', k, vec(fn.data(:).')); %#ok<AGROW>
    else
        L(end+1) = sprintf('    K.f%d_data = reshape(%s, %s);', k, vec(fn.data(:).'), mat2str(sz)); %#ok<AGROW>
    end
end
L(end+1) = '    K.loaded = true;';
L(end+1) = 'end';
L(end+1) = 'outOfEnvelope = false;';
outNames = cellfun(@(s) ['v_' matlab.lang.makeValidName(s)], {v.varID}, 'UniformOutput', false);
fnOut = {model.functions.output};
for j = model.order
    id = v(j).varID; mv = outNames{j};
    switch v(j).kind
        case 'input'
            if isnan(v(j).initialValue)
                L(end+1) = sprintf(['if isfield(in, ''%s''), %s = in.%s; else, error(''vital:daveml:missingInput'', ' ...
                    '''required input "%s" (%s) not supplied''); end'], id, mv, id, id, v(j).name); %#ok<AGROW>
            else
                L(end+1) = sprintf('if isfield(in, ''%s''), %s = in.%s; else, %s = %.17g; end', ...
                    id, mv, id, mv, v(j).initialValue); %#ok<AGROW>
            end
        case 'constant'
            if isnan(v(j).initialValue)
                error('vital:daveml:undefinedVariable', 'variable "%s" has no input, value, calculation or function.', id);
            end
            L(end+1) = sprintf('%s = %.17g;', mv, v(j).initialValue); %#ok<AGROW>
        case 'calc'
            L(end+1) = sprintf('%s = %s;', mv, v(j).expr); %#ok<AGROW>
        case 'function'
            k = find(strcmp(fnOut, id), 1);
            fn = model.functions(k);
            bpList = strjoin(arrayfun(@(b) sprintf('K.f%d_bp%d', k, b), 1:numel(fn.bps), 'UniformOutput', false), ', ');
            xs = strjoin(cellfun(@(s) ['v_' matlab.lang.makeValidName(s)], fn.inputs, 'UniformOutput', false), ', ');
            ex = strjoin(cellfun(@(s) ['''' s ''''], fn.extrapolate, 'UniformOutput', false), ', ');
            L(end+1) = sprintf('[%s, c_] = vital.daveml.lookup({%s}, K.f%d_data, [%s], {%s}, %s, %s);', ...
                mv, bpList, k, xs, ex, vec(fn.lo), vec(fn.hi)); %#ok<AGROW>
            L(end+1) = 'outOfEnvelope = outOfEnvelope || c_;'; %#ok<AGROW>
    end
    if isfinite(v(j).minValue)
        L(end+1) = sprintf('%s = max(%s, %.17g);', mv, mv, v(j).minValue); %#ok<AGROW>
    end
    if isfinite(v(j).maxValue)
        L(end+1) = sprintf('%s = min(%s, %.17g);', mv, mv, v(j).maxValue); %#ok<AGROW>
    end
end
for j = 1:numel(v)
    L(end+1) = sprintf('out.%s = %s;', v(j).varID, outNames{j}); %#ok<AGROW>
end
L(end+1) = 'out.outOfEnvelope = outOfEnvelope;';
L(end+1) = 'end';
if ~isfolder(folder), mkdir(folder); end
f = fullfile(folder, [name '.m']);
fid = fopen(f, 'w');
if fid < 0, error('vital:daveml:cannotWrite', 'cannot write %s', f); end
fprintf(fid, '%s\n', L);
fclose(fid);
clear(name);                     % make MATLAB pick up a regenerated file
end

function s = vec(x)
parts = arrayfun(@(a) sprintf('%.17g', a), x, 'UniformOutput', false);
parts = strrep(parts, 'Inf', 'Inf');
s = ['[' strjoin(parts, ' ') ']'];
end
