function out = inertia(in)
%INERTIA  GENERATED by vital.daveml.compile. DO NOT EDIT.
%   Source: F16_inertia.dml (F-16 inertia model (a la Stevens & Lewis))
%   Source SHA-256: e11d4eba5b158d24db7034bd85682ad0b896dd2f3172f007ca3d6d6d4e693c4a
%   Inputs and outputs are in the units declared by the source file.
%   Regenerate with vital.aircraft.f16.generateModels (F-16) or vital.daveml.compile.
persistent K
if isempty(K)
    K.loaded = true;
end
outOfEnvelope = false;
if isfield(in, 'CG_PCT_MAC'), v_CG_PCT_MAC = in.CG_PCT_MAC; else, v_CG_PCT_MAC = 35; end
v_CBAR = 11.32;
v_XIXX = 9496;
v_XIYY = 55814;
v_XIZZ = 63100;
v_XIZX = 982;
v_XIXY = 0;
v_XIYZ = 0;
v_XMASS = 637.15949999999998;
v_DYCG = 0;
v_DZCG = 0;
v_DXCG = (0.01 * v_CBAR * (35 - v_CG_PCT_MAC));
out.CG_PCT_MAC = v_CG_PCT_MAC;
out.CBAR = v_CBAR;
out.XIXX = v_XIXX;
out.XIYY = v_XIYY;
out.XIZZ = v_XIZZ;
out.XIZX = v_XIZX;
out.XIXY = v_XIXY;
out.XIYZ = v_XIYZ;
out.XMASS = v_XMASS;
out.DYCG = v_DYCG;
out.DZCG = v_DZCG;
out.DXCG = v_DXCG;
out.outOfEnvelope = outOfEnvelope;
end
