function out = prop(in)
%PROP  GENERATED by vital.daveml.compile. DO NOT EDIT.
%   Source: F16_prop.dml (F-16 propulsion model (a la Stevens & Lewis))
%   Source SHA-256: e5fd7772e5c05cdac666c94febbe4cb50139418b26045affd92dbd198f2215c6
%   Inputs and outputs are in the units declared by the source file.
%   Regenerate with vital.aircraft.f16.generateModels (F-16) or vital.daveml.compile.
persistent K
if isempty(K)
    K.f1_bp1 = [0 0.20000000000000001 0.40000000000000002 0.59999999999999998 0.80000000000000004 1];
    K.f1_bp2 = [0 10000 20000 30000 40000 50000];
    K.f1_data = reshape([1060 635 60 -1020 -2700 -3600 670 425 25 -710 -1900 -1400 880 690 345 -300 -1300 -595 1140 1010 755 350 -247 -342 1500 1330 1130 910 600 -200 1860 1700 1525 1360 1100 700], [6 6]);
    K.f2_bp1 = [0 0.20000000000000001 0.40000000000000002 0.59999999999999998 0.80000000000000004 1];
    K.f2_bp2 = [0 10000 20000 30000 40000 50000];
    K.f2_data = reshape([12680 12680 12610 12640 12390 11680 9150 9150 9312 9839 10176 9848 6200 6313 6610 7090 7750 8050 3950 4040 4290 4660 5320 6100 2450 2470 2600 2840 3250 3800 1400 1400 1560 1660 1930 2310], [6 6]);
    K.f3_bp1 = [0 0.20000000000000001 0.40000000000000002 0.59999999999999998 0.80000000000000004 1];
    K.f3_bp2 = [0 10000 20000 30000 40000 50000];
    K.f3_data = reshape([20000 21420 22700 24240 28070 28885 15000 15700 16860 18910 21075 23319 10800 11225 12250 13760 15975 18300 7000 7323 8154 9285 11115 13484 4000 4435 5000 5700 6860 8642 2500 2600 2835 3215.3000000000002 3950 5057], [6 6]);
    K.loaded = true;
end
outOfEnvelope = false;
if isfield(in, 'PWR'), v_PWR = in.PWR; else, v_PWR = 0; end
if isfield(in, 'ALT'), v_ALT = in.ALT; else, v_ALT = 0; end
if isfield(in, 'RMACH'), v_RMACH = in.RMACH; else, v_RMACH = 0; end
v_MIL_PWR = 50;
[v_T_IDLE, c_] = vital.daveml.lookup({K.f1_bp1, K.f1_bp2}, K.f1_data, [v_RMACH, v_ALT], {'neither', 'neither'}, [0 0], [1 50000]);
outOfEnvelope = outOfEnvelope || c_;
[v_T_MIL, c_] = vital.daveml.lookup({K.f2_bp1, K.f2_bp2}, K.f2_data, [v_RMACH, v_ALT], {'neither', 'neither'}, [0 0], [1 50000]);
outOfEnvelope = outOfEnvelope || c_;
[v_T_MAX, c_] = vital.daveml.lookup({K.f3_bp1, K.f3_bp2}, K.f3_data, [v_RMACH, v_ALT], {'neither', 'neither'}, [0 0], [1 50000]);
outOfEnvelope = outOfEnvelope || c_;
v_FEX = vital.daveml.piecewise([(v_PWR < v_MIL_PWR)], [(v_T_IDLE + ((v_PWR * (v_T_MIL - v_T_IDLE)) / v_MIL_PWR))], (v_T_MIL + (((v_PWR - v_MIL_PWR) * (v_T_MAX - v_T_MIL)) / (100 - v_MIL_PWR))));
v_FEY = 0;
v_FEZ = 0;
v_TEL = 0;
v_TEM = 0;
v_TEN = 0;
out.PWR = v_PWR;
out.ALT = v_ALT;
out.RMACH = v_RMACH;
out.MIL_PWR = v_MIL_PWR;
out.T_IDLE = v_T_IDLE;
out.T_MIL = v_T_MIL;
out.T_MAX = v_T_MAX;
out.FEX = v_FEX;
out.FEY = v_FEY;
out.FEZ = v_FEZ;
out.TEL = v_TEL;
out.TEM = v_TEM;
out.TEN = v_TEN;
out.outOfEnvelope = outOfEnvelope;
end
