function out = brick_aero(in)
%BRICK_AERO  GENERATED by vital.daveml.compile. DO NOT EDIT.
%   Source: brick_aero.dml (Example brick aerodynamic model)
%   Source SHA-256: a5883cfbde33969296a9578ac467e06e5920c5c1dc036d9ff654e111185af31d
%   Inputs and outputs are in the units declared by the source file.
%   Regenerate with vital.aircraft.f16.generateModels (F-16) or vital.daveml.compile.
persistent K
if isempty(K)
    K.loaded = true;
end
outOfEnvelope = false;
v_SWING = 0.22222;
v_BSPAN = 0.33333000000000002;
v_CBAR = 0.66666999999999998;
v_CLP_DAMPING = -1;
v_CLR_DAMPING = 0;
v_CMQ_DAMPING = -1;
v_CNP_DAMPING = 0;
v_CNR_DAMPING = -1;
if isfield(in, 'VRW'), v_VRW = in.VRW; else, error('vital:daveml:missingInput', 'required input "VRW" (trueAirspeed) not supplied'); end
v_VRW = max(v_VRW, 0.5);
if isfield(in, 'PB'), v_PB = in.PB; else, error('vital:daveml:missingInput', 'required input "PB" (bodyAngularRate_Roll) not supplied'); end
if isfield(in, 'QB'), v_QB = in.QB; else, error('vital:daveml:missingInput', 'required input "QB" (bodyAngularRate_Pitch) not supplied'); end
if isfield(in, 'RB'), v_RB = in.RB; else, error('vital:daveml:missingInput', 'required input "RB" (bodyAngularRate_Yaw) not supplied'); end
v_PBO2V = ((v_PB * v_BSPAN) / (2 * v_VRW));
v_QCO2V = ((v_QB * v_CBAR) / (2 * v_VRW));
v_RBO2V = ((v_RB * v_BSPAN) / (2 * v_VRW));
v_CL = 0;
v_CD = 0.01;
v_CY = 0;
v_Cl = ((v_CLP_DAMPING * v_PBO2V) + (v_CLR_DAMPING * v_RBO2V));
v_Cm = (v_CMQ_DAMPING * v_QCO2V);
v_Cn = ((v_CNP_DAMPING * v_PBO2V) + (v_CNR_DAMPING * v_RBO2V));
out.SWING = v_SWING;
out.BSPAN = v_BSPAN;
out.CBAR = v_CBAR;
out.CLP_DAMPING = v_CLP_DAMPING;
out.CLR_DAMPING = v_CLR_DAMPING;
out.CMQ_DAMPING = v_CMQ_DAMPING;
out.CNP_DAMPING = v_CNP_DAMPING;
out.CNR_DAMPING = v_CNR_DAMPING;
out.VRW = v_VRW;
out.PB = v_PB;
out.QB = v_QB;
out.RB = v_RB;
out.PBO2V = v_PBO2V;
out.QCO2V = v_QCO2V;
out.RBO2V = v_RBO2V;
out.CL = v_CL;
out.CD = v_CD;
out.CY = v_CY;
out.Cl = v_Cl;
out.Cm = v_Cm;
out.Cn = v_Cn;
out.outOfEnvelope = outOfEnvelope;
end
