function out = brick_inertia(in)
%BRICK_INERTIA  GENERATED by vital.daveml.compile. DO NOT EDIT.
%   Source: brick_inertia.dml (Example brick inertia model)
%   Source SHA-256: eae595902d2f2a6cd96632536ecbd4e55681b66dc3f6bdc22dbe2882247fbfa1
%   Inputs and outputs are in the units declared by the source file.
%   Regenerate with vital.aircraft.f16.generateModels (F-16) or vital.daveml.compile.
persistent K
if isempty(K)
    K.loaded = true;
end
outOfEnvelope = false;
v_XIXX = 0.0018942200000000001;
v_XIYY = 0.0062110189999999999;
v_XIZZ = 0.0071946650000000003;
v_XIZX = 0;
v_XIXY = 0;
v_XIYZ = 0;
v_XMASS = 0.15540475400000001;
v_DXCG = 0;
v_DYCG = 0;
v_DZCG = 0;
out.XIXX = v_XIXX;
out.XIYY = v_XIYY;
out.XIZZ = v_XIZZ;
out.XIZX = v_XIZX;
out.XIXY = v_XIXY;
out.XIYZ = v_XIYZ;
out.XMASS = v_XMASS;
out.DXCG = v_DXCG;
out.DYCG = v_DYCG;
out.DZCG = v_DZCG;
out.outOfEnvelope = outOfEnvelope;
end
