function out = cannonball_aero(in)
%CANNONBALL_AERO  GENERATED by vital.daveml.compile. DO NOT EDIT.
%   Source: cannonball_aero.dml (Example cannonball aerodynamic model)
%   Source SHA-256: baabd6eec679445cd3d5aa5d51b39ade99064c515876dfe018fae78b3eb028e5
%   Inputs and outputs are in the units declared by the source file.
%   Regenerate with vital.aircraft.f16.generateModels (F-16) or vital.daveml.compile.
persistent K
if isempty(K)
    K.loaded = true;
end
outOfEnvelope = false;
v_SWING = 0.19634950000000001;
v_CL = 0;
v_CD = 0.10000000000000001;
v_CY = 0;
v_Cl = 0;
v_Cm = 0;
v_Cn = 0;
out.SWING = v_SWING;
out.CL = v_CL;
out.CD = v_CD;
out.CY = v_CY;
out.Cl = v_Cl;
out.Cm = v_Cm;
out.Cn = v_Cn;
out.outOfEnvelope = outOfEnvelope;
end
