function out = cannonball_inertia(in)
%CANNONBALL_INERTIA  GENERATED by vital.daveml.compile. DO NOT EDIT.
%   Source: cannonball_inertia.dml (Example cannonball inertia model)
%   Source SHA-256: c00b9047ce9fd4a8ec4185c02be3fb755bb966680c501fe5d815bed1e2c61a9c
%   Inputs and outputs are in the units declared by the source file.
%   Regenerate with vital.aircraft.f16.generateModels (F-16) or vital.daveml.compile.
persistent K
if isempty(K)
    K.loaded = true;
end
outOfEnvelope = false;
v_XIXX = 3.6000000000000001;
v_XIYY = 3.6000000000000001;
v_XIZZ = 3.6000000000000001;
v_XIZX = 0;
v_XIXY = 0;
v_XIYZ = 0;
v_XMASS = 1;
v_DXCG = 0;
v_DYCG = 0;
v_DZCG = 0;
out.XIXX = v_XIXX;
out.XIYY = v_XIYY;
out.XIZZ = v_XIZZ;
out.XIZX = v_XIZX;
out.XIXY = v_XIXY;
out.XIYZ = v_XIYZ;
out.XMASS = v_XMASS;
out.DXCG = v_DXCG;
out.DYCG = v_DYCG;
out.DZCG = v_DZCG;
out.outOfEnvelope = outOfEnvelope;
end
