function AC = vehicle(name, overrides)
%VEHICLE  NESC atmospheric test vehicles for vital.plant.derivativesRotating (SI).
%   AC = vital.nesc.vehicle('cannonball')          sphere, TM Vol II B.1.1 Tables 1-2
%   AC = vital.nesc.vehicle('brick')               brick, TM Vol II B.1.3 Tables 4-5
%   AC = vital.nesc.vehicle(name, overrides)       overrides: struct of aero
%        output coefficients replaced by the case (e.g. struct('CD', 0) for
%        case 1; CD = Cl = Cm = Cn = 0 for case 2; proposed ADR N9)
%   Mass, inertia and reference geometry come from the compiled DAVE-ML models
%   (vital.models.nesc.*_inertia / *_aero, generated by vital.nesc.generateModels);
%   the CM is the reference point (DXCG = DYCG = DZCG = 0 in both inertia files).
%   Loads: vital.nesc.bodyLoads. No AC.limits: these bodies have no alpha/beta
%   table envelope, so vital.sim.run's default envelope guard is off.
arguments
    name (1,:) char {mustBeMember(name, {'cannonball', 'brick'})}
    overrides (1,1) struct = struct()
end
k = vital.units.constants();
switch name
    case 'cannonball'
        ine = vital.models.nesc.cannonball_inertia(struct());
        aer = vital.models.nesc.cannonball_aero(struct());
        % no reference lengths in cannonball_aero.dml; the 6-in diameter
        % (cannonball_inertia.dml header) is used only by air-data rates (unused)
        AC.S = aer.SWING * k.ft^2; AC.b = 0.5 * k.ft; AC.cbar = 0.5 * k.ft;
        AC.aeroModel = @vital.models.nesc.cannonball_aero;
    case 'brick'
        ine = vital.models.nesc.brick_inertia(struct());
        aer = vital.models.nesc.brick_aero(struct('VRW', 1, 'PB', 0, 'QB', 0, 'RB', 0));
        AC.S = aer.SWING * k.ft^2; AC.b = aer.BSPAN * k.ft; AC.cbar = aer.CBAR * k.ft;
        AC.aeroModel = @vital.models.nesc.brick_aero;
end
AC.name = name;
AC.mass = ine.XMASS * k.slug;
AC.J = vital.mass.inertiaTensor(ine.XIXX, ine.XIYY, ine.XIZZ, ine.XIXY, ine.XIZX, ine.XIYZ) * k.slugft2;
AC.r_cg = [ine.DXCG; ine.DYCG; ine.DZCG] * k.ft;
AC.r_mrc = [0; 0; 0];
AC.overrides = overrides;
AC.loadsFcn = @vital.nesc.bodyLoads;
AC.controlNames = {};
end
